[package]
authors = [
  "Jorge Aparicio <jorge@japaric.io>",
  "Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"
]
categories = ["asynchronous", "embedded", "hardware-support", "no-std"]
description = " A Hardware Abstraction Layer (HAL) for embedded systems "
documentation = "https://docs.rs/embedded-hal"
keywords = ["hal", "IO"]
license = "MIT OR Apache-2.0"
name = "embedded-hal"
readme = "README.md"
repository = "https://github.com/japaric/embedded-hal"
version = "0.1.2"

[dependencies.nb]
version = "0.1.1"
git = "https://github.com/Nemo157/nb"
branch = "io-traits"

[dev-dependencies]
stm32f30x = "0.6.0"
futures = "0.1.17"

[features]
unproven = ["nb/unstable"]
