on:
  push: # Run CI for all branches except GitHub merge queue tmp branches
    branches-ignore:
    - "gh-readonly-queue/**"
  pull_request: # Run CI for PRs on any branch
  merge_group: # Run CI for the GitHub merge queue

name: Continuous integration

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@beta
      - run: cargo test --workspace
  
  test-all-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@beta
      - run: cargo test --workspace --all-features

  build-nostd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@beta
        with:
          target: thumbv7m-none-eabi
      - run: >
          cargo build
          --workspace
          --target thumbv7m-none-eabi
          --features async,defmt-03

  msrv-1-60:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.60
      - run: >
          cargo test
          -p embedded-hal:1.0.0-rc.2
          -p embedded-hal-bus
          -p embedded-hal-nb
          -p embedded-io
          -p embedded-io-adapters
          -p embedded-can

  msrv-1-75:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@beta
      - run: cargo test --workspace --all-features
